<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NextStep</name>
   <tag></tag>
   <elementGuidId>4b77b1c7-b110-43f0-b9c1-ef7593c4ce92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@automation-id = 'newStaffMemberGotoUploadContractButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00863406-2af9-428d-8e55-4adf74e9951f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation-id</name>
      <type>Main</type>
      <value>newStaffMemberGotoUploadContractButton</value>
      <webElementGuid>4c6e244e-d14c-4848-83df-1130828506f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
