<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ApplicantEmail</name>
   <tag></tag>
   <elementGuidId>e7bfc167-a110-46c2-8984-b8f123e2805d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@automation-id = 'newStaffMemberEmailInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b551801b-fa10-4de7-865a-098e6d250d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_602df3a0-fc6d-45c9-a9d9-090a30e0a4f6</value>
      <webElementGuid>a1d33acd-faba-4d4f-a44a-b983670c9afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-field__native q-placeholder</value>
      <webElementGuid>1554744c-d8b6-42f4-a4e3-7454e50e4a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation-id</name>
      <type>Main</type>
      <value>newStaffMemberEmailInput</value>
      <webElementGuid>a00c5433-9b01-47fc-a2f1-f625acd6df4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Applicant's email</value>
      <webElementGuid>bda73c13-a22e-422c-acd7-8c3caed47663</webElementGuid>
   </webElementProperties>
</WebElementEntity>
