<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Facebook</name>
   <tag></tag>
   <elementGuidId>ff23e7a3-a0e4-42fc-855d-65234355ee8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[2]//img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>43c698d6-29ee-41cb-93fe-d2475b9bf442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[2]//img[1]</value>
      <webElementGuid>fe5c0f1b-203f-45be-936f-5cd49cf6af6c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
