<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Twitter</name>
   <tag></tag>
   <elementGuidId>3eb6e0db-5b4f-4575-8e7d-fc12d3d111b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[3]//img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>488b09b7-703e-4435-887a-495e319f3654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[3]//img[1]</value>
      <webElementGuid>0d8d5205-f2ab-4afe-97b5-fefd09381c76</webElementGuid>
   </webElementProperties>
</WebElementEntity>
