<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Youtube</name>
   <tag></tag>
   <elementGuidId>c6037f7e-11fe-43d2-af34-992b6c8566b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[4]//img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad3e0aeb-c0be-4dd9-9d5c-18c9e89cea24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[4]//img[1]</value>
      <webElementGuid>f422f5ac-9b17-4828-bcad-93e2fba04d18</webElementGuid>
   </webElementProperties>
</WebElementEntity>
