<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_LinkedIn</name>
   <tag></tag>
   <elementGuidId>8ab06378-e66e-4442-8bd7-05398231ddc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[1]//img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d5bcd625-3b22-4a06-aba2-1d313b612b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[1]//img[1]</value>
      <webElementGuid>1921625d-4d7c-4b76-a814-a010d0df1db2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
