<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_OrangeHRM</name>
   <tag></tag>
   <elementGuidId>651e3a77-2ef0-4bf6-871c-9c668eb237e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='divLogo']//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>842c37cf-26a9-41f1-969e-39f72e2b716a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='divLogo']//img</value>
      <webElementGuid>21e55c23-1f5c-4d91-adb5-53fd6d55cae0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
