<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_LoginPanel</name>
   <tag></tag>
   <elementGuidId>66c51637-a43f-4b89-a14c-50126def72a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'logInPanelHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98601a06-6703-470d-933d-95d948684fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logInPanelHeading</value>
      <webElementGuid>404a7cb0-c2da-44e1-b5b7-3ad76bd0b74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='logInPanelHeading']</value>
      <webElementGuid>3c3b8f83-3f9e-445c-bd92-7d006ed429b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
