<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_PasswordHint</name>
   <tag></tag>
   <elementGuidId>93c19b3f-202f-4be2-a0e0-e4b1b7749667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'form-hint' and (contains(text(), 'Password') or contains(., 'Password'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b92ffad1-132d-4f5b-b711-19114f4fbaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-hint</value>
      <webElementGuid>f56e86b8-b4bf-4889-85c2-3b5dc3d22885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>e187d684-8576-4ff1-93e4-80cc11cd8856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='form-hint'][contains(text(),'Username')]</value>
      <webElementGuid>c92ff460-5f01-417f-8d72-de5ef93d2eb3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
