<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_MyInfo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c70e5b44-4a48-4de5-8363-2dbf6e49e02c</testSuiteGuid>
   <testCaseLink>
      <guid>c1f183af-77d7-4733-b752-1ff5ba7957e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-114_VerifyESSUserLoginSuccessfully</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac652e39-3f12-48f0-beb3-12e5ed1b2163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64c9ac69-7b0a-4ce5-ac6a-3542d3443b6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4683cedd-9284-4d27-9d1d-9ac21c7c9e06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-115_VerifyItemsMyInfo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac5ae1ad-e6d8-45f5-85bf-0e42f4e78b61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>632aaafc-9d65-47b4-8f62-e928d6c7b3ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40655415-94db-4395-a06b-2c5d3f42d4b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-117_VerifyRestrictedFields_ESSUser</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>672a4660-fbad-438a-93ac-6659ebac6a4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57a7e2a7-4a1c-4917-abfb-853132dc9318</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1eae0b5a-8f77-4115-8760-98ffc8423ee2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-154_VerifyRestrictedFields_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7915cef-a90f-4f20-a4e2-380b513b8044</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1887c1c-69ec-4b4d-b747-dd6fd8528316</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>593b0c68-6ea2-473d-b500-41e0c9098c5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-121_VerifyErrorMessageForRequiredField_PersonalDetails</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7df5690-fff8-4c17-87ff-45f749c66c56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39aa0d8e-fa30-4cc7-9ff2-04cc06b5eba1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>781e1b74-3f9b-4cf5-84a8-f927558e39bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-122_VerifyErrorMessageForIncorrectFormatDate_PersonalDetails</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17682e84-9241-4b95-951c-94608dd6cf9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c932adb1-e0a9-4d85-91a4-dac20fb171c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1e785f3-b66a-4c7a-b4be-6b81803bdd5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-126_VerifyTextFieldsAutoTruncate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aa03f49-42bf-4826-a478-0fcc550502f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dbf8401-4800-42a2-934a-2a9d0e8b9f09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30b0959b-c95b-448d-9a1d-257c263195ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-127_VerifyEditPersonalDetails</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>680efa95-280a-4bb4-8985-66c31f8dfd84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbe967c1-4a5c-45a8-8ae1-5903dcd86e8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49755b88-e6af-4e87-bb35-fa8d1aa1fa09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-129_VerifyEditCustomFields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df88d9a0-40a4-419d-b280-b4b176e0e432</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18b8b7d5-00c6-46ca-a55f-4ac46bf0cf84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa41a51b-6a0f-417c-932d-82b3c6345ec1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-131_VerifyErrorMessageForRequiredField_Attachments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7461531a-3aca-4948-b041-420f9b603368</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>580ec997-64cc-44da-9c07-5eaf9512db82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2fab31d-b54f-463e-8188-fba2fcf86aa7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-142_VerifyUploadFileLessThan1MB</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7a6bef-feb6-490b-ad5f-aa2c64d9bab7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ec3e1ab-07bd-4270-b845-44147329c9ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a42cf1f9-1737-41dd-a0b0-36f0ecf36c5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-143_VerifyUploadFile1MB</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaaddd61-7812-4abc-8f14-43ec057e0e73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b72c1e72-c2fb-44b2-ada9-30d75521287a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d625428-84d3-402f-ac44-6373aec3a3dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-144_VerifyUploadFileMoreThan1MB</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16ddd40d-99b3-44a8-a13b-ea2804f91084</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7da5ba8e-13ae-499d-b85f-b34be414df44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6cd39c1-5b70-4d88-9c09-969849d9dd01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-145_VerifyEditAttachment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>165de1a1-b741-4dc4-8027-561717e83129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eae880a1-1e79-48c1-b30c-ebec69a71355</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>761c2d69-c6c8-469a-8192-c03ba8b70d25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-152_VerifyDownloadAttachment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41e54ad7-c191-4f14-b1c1-fcd3d3c34f45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebbef894-73d0-49e9-8e7b-3bf81e766f72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>568f3956-fd4c-42b2-80e5-7614ab7ee50a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-153_VerifyDeleteAttachment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>508157ed-f65a-4bfb-a49e-23615a46d89b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c0a09c2-cd06-405e-9e0b-dc4de186e6f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd6e64bb-a173-4978-8c0b-374b0fbaca8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-155_VerifyCheckAllCheckbox</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7f5f610-8fac-46c7-8cc6-ae88160bd9f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd9b7519-5c55-4971-a105-636f6023ffbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba3f9ae7-6fb9-4124-a4d7-6ff48b4542c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyInfo/HR-156_VerifyDeleteAllAttachments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7da6a6b4-051f-4dcb-acc9-14fda4c5e7c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9276c41c-f6aa-40c6-ab4c-fa23310a4c4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e9eaac9-c441-4495-9008-4b380deddb3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/MyInfo/Test</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>881758d9-2e3a-4b12-9f75-957a51f91656</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccbcbbc7-8fa5-4377-86f3-73f27ee0e8f7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
