<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_MaritalStatus</name>
   <tag></tag>
   <elementGuidId>4b71691d-4203-44ce-9d68-f4347ae73ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'personal_cmbMarital']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>95bf518d-dcae-485e-af9c-10657e9f9635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_cmbMarital</value>
      <webElementGuid>9fea14c5-4bea-4341-a64a-f92745f2237f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[cmbMarital]</value>
      <webElementGuid>e1b68800-6343-4d19-9e4a-bf0e16b1dd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>e785d976-dbe8-42e6-9d60-9d18ceb228a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='personal_cmbMarital']</value>
      <webElementGuid>faaa6bbf-f4fe-48e4-a871-6f3ec7bf665e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
