<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_DatepickerMonth</name>
   <tag></tag>
   <elementGuidId>7eefa225-911d-46a2-b928-eb47b6e9764e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@class = 'ui-datepicker-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dfea2943-f359-46ab-9b38-65c9bd6dc578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-month</value>
      <webElementGuid>0a7dbb9a-3992-4ac5-9c4c-7a3632316439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@class='ui-datepicker-month']</value>
      <webElementGuid>b9b9bece-fdff-4841-9b5a-4666861b04d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
