<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_BloodType</name>
   <tag></tag>
   <elementGuidId>5a70bea1-a395-4472-9b3c-44b31afd3124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'custom1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3fad3aed-9407-4066-a5ab-472311a9c6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>custom1</value>
      <webElementGuid>385386e1-ab6d-4ac9-aed8-9d82922c1810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>12675b17-8d38-4ee2-a1ee-cbb397466e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name='custom1']</value>
      <webElementGuid>7674715e-a609-4d47-9b70-94181b92959c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
