<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>heading_Attachments</name>
   <tag></tag>
   <elementGuidId>f7abf216-3451-420b-b791-661f3e4471de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h1[(contains(text(), 'Attachments') or contains(., 'Attachments'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>83cc53d9-712d-4fc1-bfea-de5cd7f8263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attachments</value>
      <webElementGuid>5d8fec2a-36f5-4cc2-b9ac-c40533266cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h1[contains(text(),'Attachments')]</value>
      <webElementGuid>eb4f1179-052c-4da7-907e-2fee10bf4027</webElementGuid>
   </webElementProperties>
</WebElementEntity>
