<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Picture</name>
   <tag></tag>
   <elementGuidId>ae2f0153-9669-46d4-87ac-35f3a60f6506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@id = 'empPic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2dd7482b-cc68-4838-a81c-bd143bd1e124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empPic</value>
      <webElementGuid>bc9a6ee5-073c-4c3a-87c4-f8969be901d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@id='empPic']</value>
      <webElementGuid>ecec3920-1416-4c94-be34-a9fdd048f155</webElementGuid>
   </webElementProperties>
</WebElementEntity>
