<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_CalendarBirthday</name>
   <tag></tag>
   <elementGuidId>072c44c4-5601-4a32-845b-e12fcac6483b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ol[3]//li[4]//img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>18b6967b-42d8-4195-84f2-b7eea7ef30e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>342671e5-0eaf-4fd8-b890-0cc0f8cb5d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ol[3]//li[4]//img[1]</value>
      <webElementGuid>754b1692-d086-46a9-b42f-5b1547d2e052</webElementGuid>
   </webElementProperties>
</WebElementEntity>
