<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MiddleName</name>
   <tag></tag>
   <elementGuidId>b7daf264-69f3-4166-8bf3-3a2a55c79f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'personal_txtEmpMiddleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3eb856e7-5c97-43bb-8094-fbb7ce174f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtEmpMiddleName</value>
      <webElementGuid>8cb7aae8-11fd-4c06-a873-3ad611070f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtEmpMiddleName]</value>
      <webElementGuid>798be337-3a43-4192-8dc3-b4da09113968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block default editable</value>
      <webElementGuid>a1554e12-b9ba-4e48-9b60-f940f0dcc793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='personal_txtEmpMiddleName']</value>
      <webElementGuid>eeb035ab-2a4b-4236-a31d-e0307b9a86e3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
