<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ReplaceWith</name>
   <tag></tag>
   <elementGuidId>947e2d00-f1fb-444b-99ab-648247bfc5dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'selectFileSpan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c89533ec-c277-4717-8588-9558fc7b925d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectFileSpan</value>
      <webElementGuid>2eb5c596-0d22-4440-a099-4a672d1529b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@id='selectFileSpan']</value>
      <webElementGuid>6bf4ec55-ce00-4d67-ac0d-f44c8b054dda</webElementGuid>
   </webElementProperties>
</WebElementEntity>
