<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Gender</name>
   <tag></tag>
   <elementGuidId>7aece2bd-974d-448a-b997-2f37aefd27a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[(contains(text(), 'Gender') or contains(., 'Gender'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>09a3aa9f-eb1f-4257-9089-2a27c18cfdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>af570ce5-67a5-4324-ab6c-080f003b30fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(text(),'Gender')]</value>
      <webElementGuid>b697b455-824d-47bd-9ea2-c055a2ff6231</webElementGuid>
   </webElementProperties>
</WebElementEntity>
