<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_MaxFileSize</name>
   <tag></tag>
   <elementGuidId>37aabd11-685b-4132-894d-7c760d45808b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@class = 'fieldHelpBottom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b173c8d7-9dd4-4635-9c9c-4d8cfb028236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fieldHelpBottom</value>
      <webElementGuid>d311839a-f128-4555-b045-933da6298aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@class='fieldHelpBottom']</value>
      <webElementGuid>afce4d0a-3496-45da-a20d-f983237974b3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
