<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ErrorMessageLastName</name>
   <tag></tag>
   <elementGuidId>f07b2111-b888-4b40-91cb-3696cf5b2061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@for = 'personal_txtEmpLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c361a0dd-5d8e-4d9e-a5ca-8ddf7d1c2556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-error</value>
      <webElementGuid>a45b5350-cbca-420b-9d07-320b56617cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>personal_txtEmpLastName</value>
      <webElementGuid>a1adcb57-5813-4102-87f1-0ed8d269cac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[3]//span[1]</value>
      <webElementGuid>f10c6b88-4638-4d9a-a877-7dbeec980087</webElementGuid>
   </webElementProperties>
</WebElementEntity>
