<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_SeclectFile</name>
   <tag></tag>
   <elementGuidId>8b039b8d-e860-4dfb-85dc-3d8f14df2c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'selectFileSpan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f6270cb4-9ddb-4996-93c2-094494f6221c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectFileSpan</value>
      <webElementGuid>af956a4d-88ab-4b66-94ba-63b800d79015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@id='selectFileSpan']</value>
      <webElementGuid>ba635e96-1533-4061-a707-048c754c78cc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
