<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Job</name>
   <tag></tag>
   <elementGuidId>284494ca-956d-40a1-bfa2-68e545b95a3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(contains(text(), 'Job') or contains(., 'Job'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b3eccec-90cf-41c4-a9ce-c60ad6ace770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(text(),'Job')]</value>
      <webElementGuid>5d87efec-9372-4e63-b0b1-e82cfcaef554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job</value>
      <webElementGuid>5430cc68-36fa-45f5-b3ac-fc5016d4d5de</webElementGuid>
   </webElementProperties>
</WebElementEntity>
