<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Immigration</name>
   <tag></tag>
   <elementGuidId>05650706-1750-4464-ad12-f66de5a6efc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(contains(text(), 'Immigration') or contains(., 'Immigration'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>559e2421-7d35-49dd-87ad-dde62dd110fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(text(),'Immigration')]</value>
      <webElementGuid>b43882d3-772c-4d9f-95e0-95d8ffd95e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Immigration</value>
      <webElementGuid>07761ce6-7d84-4457-8b0a-e24a0d3ec664</webElementGuid>
   </webElementProperties>
</WebElementEntity>
