<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_MaleGender</name>
   <tag></tag>
   <elementGuidId>6c62c96f-f5ff-4e10-a669-7d91d6f1f084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'personal_optGender_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe9aab83-9b91-496e-a286-31608d04acea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_optGender_1</value>
      <webElementGuid>2c8691c0-b088-4444-ba68-254e07ad830f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[optGender]</value>
      <webElementGuid>504473ea-5128-467b-8001-81e2029d8e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>d2c1af37-cae9-4f73-83cf-f74bc7679ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='personal_optGender_1']</value>
      <webElementGuid>1c41f327-40d0-4931-b01f-3b4f211becb7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
