<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_AddAttachment</name>
   <tag></tag>
   <elementGuidId>a3db7c89-9b99-4cc8-aee3-216d73ce877d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'addPaneAttachments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59a97589-ea4e-4e17-8ebc-c3a940ff4ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addPaneAttachments</value>
      <webElementGuid>ed0fa0a6-3d76-4898-bc84-d0878a536585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='addPaneAttachments']</value>
      <webElementGuid>f87bdfda-1786-492e-9577-6b8c9d9576df</webElementGuid>
   </webElementProperties>
</WebElementEntity>
