<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_FileName</name>
   <tag></tag>
   <elementGuidId>098c7f44-ec4c-4da5-83c3-d19d98de9743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'currentFileSpan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f558a8c-968c-4e5e-939f-d63304913099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentFileSpan</value>
      <webElementGuid>79f618a4-df77-4731-99c5-44787d31ab7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='currentFileSpan']</value>
      <webElementGuid>ff3be875-2210-4fc6-b62e-dff4c70429a5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
