<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_MyTimesheet</name>
   <tag></tag>
   <elementGuidId>2f1a73c1-3078-4910-9bdc-87ec4d4858c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[3]//div[1]//a[1]//img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9ec67ce6-efeb-4e1a-b546-4dec78b5aa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[3]//div[1]//a[1]//img[1]</value>
      <webElementGuid>58b4e35f-1c9b-4294-8421-c715bb1fd948</webElementGuid>
   </webElementProperties>
</WebElementEntity>
