<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_MyLeave</name>
   <tag></tag>
   <elementGuidId>75b28e2b-6bd4-43ab-8440-818e2af966b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[2]//div[1]//a[1]//img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>21d1b442-e451-4729-a6ef-48b9f8b98437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[2]//div[1]//a[1]//img[1]</value>
      <webElementGuid>109f0143-afef-41dd-808b-db0d6d17db6d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
