<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_MyInfo</name>
   <tag></tag>
   <elementGuidId>8abfd576-64e0-4aa1-997a-278b2233d571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'menu_pim_viewMyDetails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>375b53d7-b9d2-45cd-a0ec-293ceb9a1200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_pim_viewMyDetails</value>
      <webElementGuid>c5aa810e-5cf7-475a-a0cb-1ee7901c6d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>firstLevelMenu</value>
      <webElementGuid>f6059c26-1d56-4711-b288-094f5919613c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='menu_pim_viewMyDetails']</value>
      <webElementGuid>54a44029-29ec-4b27-a648-d344b63021f3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
