<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_ApplyLeave</name>
   <tag></tag>
   <elementGuidId>b0506b3c-efa6-40a3-8b56-6ed8020dfc62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Apply Leave')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9fff6e8-0dce-4a73-b620-dc87c9ddaab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quickLinkText</value>
      <webElementGuid>5e3253bb-c1ce-4a08-91d1-9f2e6dcade3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Apply Leave')]</value>
      <webElementGuid>63878a18-5920-4a71-be3e-0ccf7a0f20fe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
